---
# tasks file for new-project

- name: Get pod
  command: kubectl get pod -n desenvolvimento
  register: pod

- name: debug pod
  debug:
    msg: "{{ pod }}"

- name: Get namespace
  command: kubectl get namespace {{ namespace }}
  retries: 10
  delay: 3
  register: getNamespace
  changed_when: no
  failed_when: no

- name: Create new-project
  shell: kubectl create namespace {{ namespace }}
  retries: 10
  delay: 3
  register: createNamespace
  until: createNamespace.rc == 0
  when:
    - getNamespace.rc > 0

- name: Debug namespace - Show message
  debug:
    msg: "{{ createNamespace }}"
  when: createNamespace is defined
